version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka1:
    build: .
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.0.9
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "OT.MDA.Test.TestTopic:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kafka2:
    build: .
    ports:
      - "9093:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.0.9
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "OT.MDA.Test.TestTopic:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kafka3:
    build: .
    ports:
      - "9094:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.0.9
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "OT.MDA.Test.TestTopic:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
